### ISSUE TITLE
Welcome to built_with_flutter Discussions!

### ISSUE THREAD

**Issue by aeiou-st** [aeiou-st/built_with_flutter#4]
### Discussed in https://github.com/aeiou-st/built_with_flutter/discussions/3

<div type='discussions-op-text'>

<sup>Originally posted by **aeiou-st** March 11, 2023</sup>

## 👋 Welcome!
  We’re using Discussions as a place to connect with other members of our community. We hope that you:
  * Ask questions you’re wondering about.
  * Share ideas.
  * Engage with other community members.
  * Welcome others and are open-minded. Remember that this is a community we
  build together 💪.

  To get started, comment below with an introduction of yourself and tell us about what you do with this community.

</div>

**Comment by aeiou-st** [comment]
it's seems like we need to implement some test cases in project

**Comment by Mujammil-ios** [comment]
>it's seems like we need to implement some test cases in the project

**Comment by Mujammil-ios** [comment]
Can you check it now
